[build]
target = "index.html"
dist = "dist"
public_url = "/"

[serve]
addresses = ["0.0.0.0"]
port = 8080
open = false

[[hooks]]
stage = "pre_build"
command = "sh"
command_arguments = ["./scripts/build-tailwind.sh"]
